### ISSUE TITLE
Import JWT token attributes to Jenkins User

### ISSUE THREAD

**Issue by maskedpirate** [jenkinsci/jwt-auth-plugin#3]
### What feature do you want to see added?

Currently the jwt-auth-plugin only provides Jenkins security realm attributes to Jenkins:
- username (from userClaimName)
- groups (from groupsClaimName)

It would be good to have additional Jenkins user attributes created/updated from the JWT including:
- email (proposed from emailClaimName)
- fullName (proposed from fullNameClaim)

It could likely be implemented similar to how [oic-auth-plugin L523](https://github.com/jenkinsci/oic-auth-plugin/blob/bef71ae42448de87f95b86feb41930357a4f872b/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L523) and L530 does.

**Comment by narcoticfresh** [comment]
@maskedpirate just FYI; I don't currently have resources to implement this feature request.. and I'm preparing for longer holidays.. if you would like to have this feature early, feel free to open a PR..

If not, I will try to implement it, but it will take a couple of months presumably..

**Comment by maskedpirate** [comment]
@narcoticfresh - I am still interested in this feature; though have not had time to try at the code myself. Have you had an opportunity to look into it any further?

**Comment by maskedpirate** [comment]
@narcoticfresh - I see some activity in the repo - any chance of merging #6 while you're doing other cleanup?

**Comment by narcoticfresh** [comment]
@maskedpirate 
ehm.. yes, i tried to resume work and implement some things.. but honestly, i don't feel comfortable to make new releases as I'm unaware of the best way to ensure that my changes will not result in bugs..

I didn't have time yet (and/or forgot how if I knew it before) to really read all the docs regarding updating the jenkins dependencies and then ensuring compatibility and functionality in the tests.. 

after the initial release, I didn't do anything anymore; leaving me to forget most of the things in the meantime ;-)

**Comment by maskedpirate** [comment]
@narcoticfresh - Would you be ok putting this plugin up for adoption? I'm interested in adopting it and I've started the process but it apparently goes faster/easier if the current maintainer says so.

**Comment by narcoticfresh** [comment]
@maskedpirate 
ya, well, maybe.. maybe i can get it up.. but first, let's get a release done, see my feedback in #6 and get this done..

**Comment by narcoticfresh** [comment]
@maskedpirate 
version `0.3.0` was just released..
